### ISSUE TITLE
Support dict in tables

### ISSUE THREAD

**Issue by smihael** [greyli/bootstrap-flask#165]
According to https://bootstrap-flask.readthedocs.io/en/stable/macros.html#render-table
data for tables can be given as list of dicts.

However, the following simple example doesn't work.

I started by adapting `test_table()` of https://github.com/greyli/bootstrap-flask/blob/1.8.0/examples/app.py

```py
@app.route('/table')
def test_table():
    messages = [dict(id='1',name='test',__table__=table)]
    titles = [('id', '#'), ('name', 'Message')]
    return render_template('table.html', messages=messages,title=titles)
```
I get the `AttributeError: 'dict' object has no attribute '__table__'`.

Bellow is the full trace (full paths omitted):

```
Traceback (most recent call last)

    File "flask/venv/lib/python3.6/site-packages/flask/app.py", line 2091, in __call__

    return self.wsgi_app(environ, start_response)

    File "flask/venv/lib/python3.6/site-packages/flask/app.py", line 2076, in wsgi_app

    response = self.handle_exception(e)

    File "flask/venv/lib/python3.6/site-packages/flask/app.py", line 2073, in wsgi_app

    response = self.full_dispatch_request()

    File "flask/venv/lib/python3.6/site-packages/flask/app.py", line 1518, in full_dispatch_request

    rv = self.handle_user_exception(e)

    File "flask/venv/lib/python3.6/site-packages/flask/app.py", line 1516, in full_dispatch_request

    rv = self.dispatch_request()

    File "flask/venv/lib/python3.6/site-packages/flask/app.py", line 1502, in dispatch_request

    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)

    File "flask/bootstrap-flask/examples/app.py", line 159, in test_table

    return render_template('table.html', messages=messages,title=titles)

    File "flask/venv/lib/python3.6/site-packages/flask/templating.py", line 150, in render_template

    ctx.app,

    File "flask/venv/lib/python3.6/site-packages/flask/templating.py", line 128, in _render

    rv = template.render(context)

    File "flask/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1304, in render

    self.environment.handle_exception()

    File "flask/venv/lib/python3.6/site-packages/jinja2/environment.py", line 925, in handle_exception

    raise rewrite_traceback_stack(source=source)

    File "flask/bootstrap-flask/examples/templates/table.html", line 2, in top-level template code

    {% from 'bootstrap/table.html' import render_table %}

    File "flask/bootstrap-flask/examples/templates/base.html", line 48, in top-level template code

    {% block content %}{% endblock %}

    File "flask/bootstrap-flask/examples/templates/table.html", line 7, in block 'content'

    {{ render_table(messages) }}

    File "flask/venv/lib/python3.6/site-packages/jinja2/runtime.py", line 828, in _invoke

    rv = self._func(*arguments)

    File "flask/venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/table.html", line 50, in template

    {% set titles = get_table_titles(data, primary_key, primary_key_title) %}

    File "flask/venv/lib/python3.6/site-packages/flask_bootstrap/__init__.py", line 43, in get_table_titles

    for k in data[0].__table__.columns.keys():

    AttributeError: 'dict' object has no attribute '__table__'
```

**Comment by greyli** [comment]
How did you call the render_table macro? Please also provide the full error traceback.

**Comment by smihael** [comment]
I updated the original comment to include full traceback.
