### ISSUE TITLE
pipenv install bootstrap-flask return unknown location

### ISSUE THREAD

**Issue by dkotama** [greyli/bootstrap-flask#31]
Im using pipenv to manage my python modules,
after i ran :
``` pipenv install bootstrap-flask ```

this error raised

flask.cli.NoAppException: While importing "main", an ImportError was raised:

```
Traceback (most recent call last):
  File "...../lib/python3.7/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File ".../main.py", line 1, in <module>
    from app import app, db
  File ".../app/__init__.py", line 7, in <module>
    from flask_bootstrap import Bootstrap
ImportError: cannot import name 'Bootstrap' from 'flask_bootstrap' (unknown location)
```

I tried to install bootstrap-flask in my global env, with 'exit' current env, and doing 
```python3 -m pip install bootstrap-flask```
same result .

Please advise, thank you

**Comment by dkotama** [comment]
running
```
from flask_bootstrap import Bootstrap
```
in the python shell returned same errors
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named flask_bootstrap
```

**Comment by dkotama** [comment]
ok so turns out we should install the 
[flask-bootstrap](https://pythonhosted.org/Flask-Bootstrap/) plugin first 
sorry basic mistake, im new to flask :)

**Comment by dkotama** [comment]
So after struggling for 2hours,
This way fixed for me

if you have the `flask-bootstrap` in your environment, you should uninstall it.
Failed to remove the Flask-Bootstrap will give you Unknown Bootstrap error, or failed render `bootstrap.load_js()` error part.

im using pipenv, so remove all the env and reinstall everything

1. Delete environment using `pipenv --rm`
2. make new pipenv `pipenv shell`
3. install everything again `pipenv install` 

Thank you
