### ISSUE TITLE
Example app error when render table

### ISSUE THREAD

**Issue by chhenning** [greyli/bootstrap-flask#97]
When go to `http://127.0.0.1:5000/table` I get:

TypeError: macro 'render_table' takes no keyword argument 'show_actions'

```
chhenning@Christians-MBP examples % flask run
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [22/Aug/2020 20:29:37] "GET / HTTP/1.1" 200 -
[2020-08-22 20:29:39,703] ERROR in app: Exception on /table [GET]
Traceback (most recent call last):
  File "/Users/chhenning/.pyenv/versions/3.7.5/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/chhenning/.pyenv/versions/3.7.5/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/chhenning/.pyenv/versions/3.7.5/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/chhenning/.pyenv/versions/3.7.5/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/chhenning/.pyenv/versions/3.7.5/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/chhenning/.pyenv/versions/3.7.5/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/chhenning/repos/bootstrap-flask/examples/app.py", line 153, in test_table
    return render_template('table.html', messages=messages, titles=titles)
  File "/Users/chhenning/.pyenv/versions/3.7.5/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/chhenning/.pyenv/versions/3.7.5/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/chhenning/.pyenv/versions/3.7.5/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/chhenning/.pyenv/versions/3.7.5/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/chhenning/.pyenv/versions/3.7.5/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/chhenning/repos/bootstrap-flask/examples/templates/table.html", line 2, in top-level template code
    {% from 'bootstrap/table.html' import render_table %}
  File "/Users/chhenning/repos/bootstrap-flask/examples/templates/base.html", line 33, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/chhenning/repos/bootstrap-flask/examples/templates/table.html", line 22, in block "content"
    {{ render_table(messages, show_actions=True,
TypeError: macro 'render_table' takes no keyword argument 'show_actions'
127.0.0.1 - - [22/Aug/2020 20:29:39] "GET /table HTTP/1.1" 500 -
```

**Comment by greyli** [comment]
Sorry, the 1.4.1 version that includes this `show_actions` parameter is not released yet, I will release it at this weekend. For now, you can just remove the `show_actions=True,` at `File "/Users/chhenning/repos/bootstrap-flask/examples/templates/table.html", line 22`.

**Comment by greyli** [comment]
Version 1.5 was released, please upgrade with following command:
```
$ pip install -U bootstrap-flask
```
